-- =============================================
-- Inicialización Base de Datos Usuarios (PostgreSQL)
-- =============================================

-- ==========================================================
-- TABLA: rol
-- ==========================================================
CREATE TABLE IF NOT EXISTS rol (
	rolid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	descripcion VARCHAR(200)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_rol_nombre
	ON rol (LOWER(nombre));

-- ==========================================================
-- TABLA: usuariologin
-- ==========================================================
CREATE TABLE IF NOT EXISTS usuariologin (
	usuariologinid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(100) NOT NULL,
	passwordhash VARCHAR(255) NOT NULL,

	rolid INT NULL,

	ultimoacceso TIMESTAMP NULL,

	activo BOOLEAN NOT NULL DEFAULT TRUE,
	requierecambiopassword BOOLEAN NOT NULL DEFAULT TRUE,

	fecharegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	fechaactualizacion TIMESTAMP NULL,

	creadopor VARCHAR(150) NULL,
	actualizadopor VARCHAR(150) NULL,
	inactivadopor VARCHAR(150) NULL,

	CONSTRAINT fk_usuariologin_rol
		FOREIGN KEY (rolid)
		REFERENCES rol (rolid)
		ON UPDATE CASCADE
		ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_usuariologin_email
	ON usuariologin (LOWER(email));

CREATE INDEX IF NOT EXISTS ix_usuariologin_rolid
	ON usuariologin (rolid);

CREATE INDEX IF NOT EXISTS ix_usuariologin_activo
	ON usuariologin (activo);

-- ==========================================================
-- TABLA: audit_logs
-- ==========================================================
CREATE TABLE IF NOT EXISTS audit_logs (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tabla_afectada VARCHAR(100) NOT NULL,
	registro_id INT NOT NULL,
	accion VARCHAR(50) NOT NULL,
	realizado_por VARCHAR(150),
	fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_tabla_registro
	ON audit_logs (tabla_afectada, registro_id);

CREATE INDEX IF NOT EXISTS ix_audit_logs_fecha_hora
	ON audit_logs (fecha_hora DESC);

-- ==========================================================
-- DATOS INICIALES
-- ==========================================================
INSERT INTO rol (nombre, descripcion)
VALUES
	('Gerente', 'Rol con acceso completo a la administración del sistema.'),
	('Administrador', 'Rol con privilegios administrativos limitados.'),
	('Mecanico', 'Rol operativo para gestión de taller y órdenes.'),
	('Cliente', 'Rol para usuarios finales del sistema.')
ON CONFLICT DO NOTHING;
